# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase-if-necessary
    groups: # patchはグループでプルリク作成
      patch-group:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
