# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # patchバージョンアップ
  - package-ecosystem: 'npm'
  - directory: '/'
  - target-branch: 'develop'
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    schedule:
      interval: 'monthly'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 1
    labels:
      - 'dependencies'
    allow:
      - dependency-type: 'all'
    versioning-strategy: increase-if-necessary
    groups: # patchはグループでプルリク作成
      patch-group:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
    # minorバージョンアップ
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
          - version-update:semver-patch
    schedule:
      interval: 'monthly'
      time: '09:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 4
    labels:
      - 'dependencies'
    allow:
      - dependency-type: 'all'
    versioning-strategy: increase-if-necessary
